apiVersion: alpha/v1
kind: CronJob
metadata:
  name: github-backup-specific
  namespace: default
spec:
  schedule:
    - "@hourly"
  reSchedulePolicy:
  runner:
    selector:
      name: my-project-runner
  stages:
    - backup
    - upload
  tasks:
    - task 1:
      stage: backup
      provider: 
        - name: github.com
          config:
            repos:
              - orgName/projectName
            orgs:
              - orgName
                exclude:
                  - orgName/projectName
    - task 2:
      stage: upload
      storage: {storageAsDefined}
      taskGroup: A