## The Provider specifies a docker image with all components
provider: yabslabs/provider/postgresql:latest

## Provide (n) schedules for when the job should be executed
## There are predefined values or use cron notation diretcly
schedule:
  - @hourly
  - @every 1h30m10s
  lifecycle:
    - 0 0 * ? JAN,FEB,NOV,DEC * *

## 
reSchedulePolicy:

##
runner:
  selector:
    name: 
  
## The stages define 
stages:
  - backup
  - compress
  - encrypt
  - upload
  - lifecycle
  - archive
  - restore

##
task 1:
  stage: backup
  source: {backupSource}
  selector: 
    runner:
  reSchedulePolicy:
  taskGroup: A
  retry: 3
  
task 2:
  stage: compress
  algorith: tar
  taskGroup: A

task 3:
  stage: encrypt
  key: HOdoadkajdpaijdiajd
  taskGroup: A

task 3:
  stage: upload
  storage: s3-nearline
  taskGroup: A

task 4:
  stage: lifecycle
  retention: 30d
  taskGroup: B

task 5:
  stage: lifecycle
  retention: 30d
  taskGroup: B

task 6:
  stage: archive
  provider: s3-nearline
  storage: s3-coldline
  retention: 30d
  allow_failure: yes

task 7:
  stage: restore
  target: {restoreTarget}